import Head from 'next/head'
import { Contact, Jumbotron, NavBar } from '../src/components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <Jumbotron />
      <Contact />
    </div>
  )
}
